### ISSUE TITLE
Help me get it working?

### ISSUE THREAD

**Issue by nebson9** [meleu/RetroPie-joystick-selection#42]
I have RetroPie 4.7.7 set up on a laptop running Ubuntu 20.04.2 LTS. I have 2 USB controllers. Here are their names:

- Bensussen Deutsch & Associates, Inc. (BDA) **Core (Plus)** Wired Controller
- Bensussen Deutsch & Associates, Inc. (BDA) **NSW** Wired Controller

I need the "Core (Plus)" controller to always be assigned to player 1 and the "NSW" Controller to always be assigned to player 2. I installed the RetroPie-joystick-selection script using the following command:

`wget -O- "https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh" | sudo bash`

I then set up a global configuration for my controllers using the “selection by name” method. Unfortunately, the script seems to have no effect. If I plug “Core (Plus)“ into the USB port on the left side of my laptop and plug “NSW“ into the USB port on the right side of my laptop, then the assignment is done correctly upon launching a game. However, if I instead put “Core (Plus)“ on the RIGHT and “NSW“ on the LEFT, the assignment is NOT done correctly. Moreover, if a game is running and I unplug both controllers, then whichever controller I plug back in first is immediately assigned to player one, and whichever controller I plug in next is assigned to player two. I have also tried accessing the joystick selection script via runcommand to make a system specific configuration, but this did not change anything.

I've included a verbose log obtained via runcommand. It shows the following error message:
`sed: can't read /opt/retropie/configs/all/joystick-selection.cfg: Permission denied`

If I uninstall the joystick-selection package via RetroPie Setup and then reinstall using the wget command listed above, then the error message will sometimes go away temporarily.

I am also including a text file containing the terminal text from my install and initial global setup. The this text file shows error messages, including:
```
ln: failed to create symbolic link '/root/RetroPie/retropiemenu/joystick_selection.sh': No such file or directory
cp: cannot stat '/opt/retropie/supplementary/joystick-selection/joystick_selection.sh': No such file or directory
'/home/ben/RetroPie-Setup/tmp/build/joystick-selection/icon.png' -> '/root/RetroPie/retropiemenu/icons/joystick_selection.png'
cp: cannot create regular file '/root/RetroPie/retropiemenu/icons/joystick_selection.png': No such file or directory
'/opt/retropie/configs/all/emulationstation/gamelists/retropie/gamelist.xml' -> '/root/RetroPie/retropiemenu/gamelist.xml'
cp: cannot create regular file '/root/RetroPie/retropiemenu/gamelist.xml': No such file or directory
grep: /root/RetroPie/retropiemenu/gamelist.xml: No such file or directory
chown: cannot access '/root/RetroPie/retropiemenu': No such file or directory
<  Traceback (most recent call last):                │
└────────────────────────────────────────────────────────────  File "/opt/retropie/supplementary/runcommand/joy2key.py", line 241, in <module>
                                                                  chars = get_hex_chars(arg)
              File "/opt/retropie/supplementary/runcommand/joy2key.py", line 147, in get_hex_chars
                      return out.decode('utf-8')
                                                AttributeError: 'NoneType' object has no attribute 'decode'
```

[install and setup.txt](https://github.com/meleu/RetroPie-joystick-selection/files/5986636/install.and.setup.txt)
[runcommand.log](https://github.com/meleu/RetroPie-joystick-selection/files/5986640/runcommand.log)

Thank you!

**Comment by GiulioCentorame** [comment]
I had the same issue with a blank install on RetroPie 4.7.1

**Comment by GiulioCentorame** [comment]
I just encountered this issue too on a blank install of RetroPie 4.7.1

**Comment by RyanfaeScotland** [comment]
Same issue here on a fresh install of RetroPie 4.7.1 using Rasberry Pi Imager.

I note the directory /root/RetroPie/retropiemenu/ does not have any .sh files in it, they are all .rp, could this be something that has changed? Regardless, there is no joystick_selection.sh or joystick_selection.rp in there.

**Comment by KevDaSilva** [comment]
I‘m getting the same error messages, can‘t get it to run
